spring.application.name=Auth

server.port=8081
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

server.servlet.context-path=/auth

# MySQL Database Configuration (Adjust 'db_name', 'username', 'password')
spring.datasource.url=jdbc:postgresql://localhost:5432/HarmoniEventManagement
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Redis Configuration (Disabled)
#spring.data.redis.host=localhost
#spring.data.redis.port=6379

# Swagger/OpenAPI (For testing your APIs later)
springdoc.api-docs.path=/api-docs

# JWT Secret Key - DO NOT COMMIT THIS TO PUBLIC REPOS
# It is recommended to use environment variables for this in production
jwt.secret=your-very-long-and-super-secret-key-that-is-at-least-256-bits-long-for-hs256

# Spring Mail Configuration (Update with your actual email credentials)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=projecttime93@gmail.com
spring.mail.password=Project@1214#
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Google OAuth2 Configuration
google.client.id=190662284666-8jsc7a0ag2kakd389ni97gahv6lcovmq.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-id=190662284666-8jsc7a0ag2kakd389ni97gahv6lcovmq.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email